apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
stringData:
  config.yaml: |
    {
      "auths": {
        "scribesecuriy.jfrog.io": {
          "auth": "c2h1YmhhbUBzY3JpYmVzZWN1cml0eS5jb206QUtDcDhuejJMdE1KYW1VbUFTS0g0THVNQ0VMOXVOWmh0VXN0bmFDVUJKSDdYb2FlVzFSUVpRYm5rV0IxbjVOSk1hSnR2VWllWQ=="
        }
      }
    }