apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "admission-controller.fullname" . }}-webhook
  labels:
    {{- include "admission-controller.labels" . | nindent 4 }}
    control-plane: {{ template "admission-controller.fullname" . }}-webhook
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "admission-controller.fullname" . }}-webhook
subjects:
- kind: ServiceAccount
  name: {{ template "admission-controller.fullname" . }}-webhook
  namespace: {{ .Release.Namespace }}
