apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "admission-controller.fullname" . }}-webhook
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "admission-controller.labels" . | nindent 4 }}
    control-plane: {{ template "admission-controller.fullname" . }}-webhook
subjects:
- kind: ServiceAccount
  name: {{ template "admission-controller.fullname" . }}-webhook
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ template "admission-controller.fullname" . }}-webhook
  apiGroup: rbac.authorization.k8s.io
