apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "admission-controller.labels" . | nindent 4 }}
    control-plane: {{ template "admission-controller.fullname" . }}-webhook
  name: {{ template "admission-controller.fullname" . }}-webhook
  namespace: {{ .Release.Namespace }}
  {{- with .Values.webhook.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
