apiVersion: v1
kind: Secret
metadata:
  labels:
    {{- include "admission-controller.labels" . | nindent 4 }}
  name: {{ template "admission-controller.fullname" . }}-scribe-cred
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
    scribe:  {{ toJson .Values.scribe | b64enc | indent 4  }}