apiVersion: apps/v1
kind: Deployment
metadata:
  name: multi-nginx-deployment
  labels:
    app: multi-nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: multi-nginx
  template:
    metadata:
      labels:
        app: multi-nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.1
        ports:
        - containerPort: 82
