apiVersion: apps/v1
kind: Deployment
metadata:
  name: multi-nginx-deployment
  labels:
    app: multi-nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: multi-nginx
  template:
    metadata:
      labels:
        app: multi-nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 82
      - name: nginx2
        image: nginx:1.14.1
        ports:
        - containerPort: 81
      - name: nginx3
        image: nginx:1.14.0
        ports:
        - containerPort: 80