
webhook:
  replicaCount: 1
  name: webhook
  image:
    repository: scribesecuriy.jfrog.io/scribe-docker-public-local/valint
    version: v0.1.4-1-admission
    pullPolicy: IfNotPresent
  env: {}
  extraArgs:
    structured: true
    verbose: 2
  # resources:
  #   limits:
  #     cpu: 500m
  #     memory: 512Mi
  #   requests:
  #     cpu: 500m
  #     memory: 256Mi
  securityContext:
    enabled: false
    runAsUser: 65532
  podSecurityContext:
    enabled: true
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
    runAsUser: 1000
    capabilities:
      drop:
        - all
  serviceAccount:
    annotations: {}
  service:
    annotations: {}
    type: ClusterIP
    port: 443
    # For nodeport, specify the following:
    #   type: NodePort
    #   nodePort: <port-number>
  secretName: ""
  webhookName: "admission.scribe.dev"


scribe:
  auth:
    # -- Scribe Client ID
    client_id: ""
    # -- Scribe Client Secret
    client_secret: ""
  service:
    enable: false

config:
  context:
    # -- Scribe Project Key
    name: ""
  admission:
    # -- Select admitted images by regex
    glob: []
    #   - .*nginx.*
    #   - .*busybox.*
  verify:
    # -- Evidence format
    input-format: attest
  attest:
    default: sigstore
    cocosign:
      storer:
        OCI:
          enable: true
          ## repo: <your repo>

## common node selector for all the pods
commonNodeSelector: {}
commonTolerations: []

# -- OCI evidence store secret name
imagePullSecrets: []

## serviceMonitor makes metrics discoverable to prometheus
serviceMonitor:
  enabled: false
